CREATE TABLE `adsb-raw` (
  `kafka_timestamp` TIMESTAMP_LTZ(3) METADATA FROM 'timestamp',
  `kafka_headers` MAP<BYTES, BYTES> NOT NULL METADATA FROM 'headers',
  message_type            VARCHAR,
  transmission_type       VARCHAR,
  session_id              VARCHAR,
  aircraft_id             VARCHAR,
  hex_ident               VARCHAR,
  flight_id               VARCHAR,
  date_message_generated  VARCHAR,
  time_message_generated  VARCHAR,
  date_message_logged     VARCHAR,
  time_message_logged     VARCHAR,
  callsign                VARCHAR,
  altitude                VARCHAR,
  ground_speed            VARCHAR,
  track                   VARCHAR,
  latitude                VARCHAR,
  longitude               VARCHAR,
  vertical_rate           VARCHAR,
  squawk                  VARCHAR,
  alert                   VARCHAR,
  emergency               VARCHAR,
  spi                     VARCHAR,
  is_on_ground            VARCHAR
) WITH (
  'connector' = 'kafka',
  'topic' = 'adsb-raw',
  'properties.group.id' = 'kafka-supervisor-flink',
  'scan.startup.mode' = 'earliest-offset',
  'properties.bootstrap.servers' = '<Confluent Cloud bootstrap server>',
  'properties.security.protocol' = 'SASL_SSL',
  'properties.sasl.mechanism' = 'PLAIN',
  'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.plain.PlainLoginModule  required username="<Confluent Cloud API Key>" password="<Confluent Cloud API Secret>";',
  'value.format' = 'csv'
);
