CREATE TABLE `adsb-raw` (
  `kafka_timestamp` TIMESTAMP_LTZ(3) METADATA FROM 'timestamp',
  `kafka_headers` MAP<BYTES, BYTES> NOT NULL METADATA FROM 'headers',
  message_type            VARCHAR,
  transmission_type       INTEGER,
  session_id              INTEGER,
  aircraft_id             INTEGER,
  hex_ident               VARCHAR,
  flight_id               INTEGER,
  date_message_generated  VARCHAR,
  time_message_generated  VARCHAR,
  date_message_logged     VARCHAR,
  time_message_logged     VARCHAR,
  callsign                VARCHAR,
  altitude                INTEGER,
  ground_speed            DOUBLE,
  track                   DOUBLE,
  latitude                DOUBLE,
  longitude               DOUBLE,
  vertical_rate           INTEGER,
  squawk                  VARCHAR,
  alert                   INTEGER,
  emergency               INTEGER,
  spi                     INTEGER,
  is_on_ground            INTEGER
) WITH (
  'connector' = 'kafka',
  'topic' = 'adsb-raw',
  'properties.group.id' = 'kafka-supervisor-flink',
  'scan.startup.mode' = 'earliest-offset',
  'properties.bootstrap.servers' = '<Confluent Cloud bootstrap server>',
  'properties.security.protocol' = 'SASL_SSL',
  'properties.sasl.mechanism' = 'PLAIN',
  'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.plain.PlainLoginModule  required username="<Confluent Cloud API Key>" password="<Confluent Cloud API Secret>";',
  'value.fields' = 'MT;TT;SID;AID;Hex;FID;DMG;TMG;DML;TML;CS;Alt;GS;Trk;Lat;Lng;VR;Sq;Alrt;Emer;SPI;Gnd',  
  'value.format' = 'csv'
);
