{
 "title": "Flight Data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Aircraft_ID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Tracked Aircraft",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT \"aircraft_id\", \nAVG(\"latitude\") as \"latitude\",\nAVG(\"longitude\") as \"longitude\",\nAVG(\"altitude\") as \"altitude\"\nFROM \"adsb-json\"\nWHERE \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \"latitude\" IS NOT NULL AND \"longitude\" IS NOT NULL AND \"altitude\" IS NOT NULL\nGROUP BY 1\n",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT \\\"aircraft_id\\\", \\nAVG(\\\"latitude\\\") as \\\"latitude\\\",\\nAVG(\\\"longitude\\\") as \\\"longitude\\\",\\nAVG(\\\"altitude\\\") as \\\"altitude\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \\\"latitude\\\" IS NOT NULL AND \\\"longitude\\\" IS NOT NULL AND \\\"altitude\\\" IS NOT NULL\\nGROUP BY 1\\n\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT \"client_id\", \nAVG(\"client_lat\") as \"latitude\",\nAVG(\"client_lon\") as \"longitude\"\nFROM \"adsb-json\"\nWHERE \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \"latitude\" IS NOT NULL AND \"longitude\" IS NOT NULL\nGROUP BY 1\n",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT \\\"client_id\\\", \\nAVG(\\\"client_lat\\\") as \\\"latitude\\\",\\nAVG(\\\"client_lon\\\") as \\\"longitude\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \\\"latitude\\\" IS NOT NULL AND \\\"longitude\\\" IS NOT NULL\\nGROUP BY 1\\n\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Aircraft Route",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT *\nFROM \"adsb-json\"\nWHERE \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \"aircraft_id\"=${Aircraft_ID} AND \"latitude\" IS NOT NULL\nAND \"longitude\" IS NOT NULL\nAND \"altitude\" IS NOT NULL",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT *\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \\\"aircraft_id\\\"=${Aircraft_ID} AND \\\"latitude\\\" IS NOT NULL\\nAND \\\"longitude\\\" IS NOT NULL\\nAND \\\"altitude\\\" IS NOT NULL\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    },
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT \"client_id\", \nAVG(\"client_lat\") as \"latitude\",\nAVG(\"client_lon\") as \"longitude\"\nFROM \"adsb-json\"\nWHERE \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \"latitude\" IS NOT NULL AND \"longitude\" IS NOT NULL\nGROUP BY 1\n",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT \\\"client_id\\\", \\nAVG(\\\"client_lat\\\") as \\\"latitude\\\",\\nAVG(\\\"client_lon\\\") as \\\"longitude\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to}) AND \\\"latitude\\\" IS NOT NULL AND \\\"longitude\\\" IS NOT NULL\\nGROUP BY 1\\n\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Total Unique Aircraft by Receiver",
   "type": "table",
   "gridPos": { "h": 22, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "SELECT\n  \"client_id\" AS \"receiver\",\n  COUNT (DISTINCT \"aircraft_id\") AS \"aircraft tracked\"\nFROM \"adsb-json\"\nWHERE \"__time\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \"__time\" <= MILLIS_TO_TIMESTAMP(${__to})\nGROUP BY 1\nORDER BY 2 DESC",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n  \\\"client_id\\\" AS \\\"receiver\\\",\\n  COUNT (DISTINCT \\\"aircraft_id\\\") AS \\\"aircraft tracked\\\"\\nFROM \\\"adsb-json\\\"\\nWHERE \\\"__time\\\" >= MILLIS_TO_TIMESTAMP(${__from}) AND \\\"__time\\\" <= MILLIS_TO_TIMESTAMP(${__to})\\nGROUP BY 1\\nORDER BY 2 DESC\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  }
 ]
}